apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: controller-alerts
  namespace: system
spec:
  groups:
  - name: controller-panic
    rules:
    - alert: reconciler-panic
      expr: controller_runtime_reconcile_panics_total{} > 0
      annotations:
        description: "controller of pod {{ $labels.pod }} experienced panic(s); count={{ $value }}"
    - alert: webhook-panic
      expr: controller_runtime_webhook_panics_total{} > 0
      annotations:
        description: "controller webhook of pod {{ $labels.pod }} experienced panic(s); count={{ $value }}"
  - name: resource-usage
    rules:
    - alert: oom-events
      expr: container_oom_events_total > 0
      annotations:
        description: "container {{ $labels.container }} of pod {{ $labels.pod }} experienced OOM event(s); count={{ $value }}"
    - alert: operator-controller-memory-growth
      expr: deriv(sum(container_memory_working_set_bytes{pod=~"operator-controller.*",container="manager"})[5m:]) > 100_000
      for: 5m
      keep_firing_for: 1d
      annotations:
        description: "operator-controller pod memory usage growing at a high rate for 5 minutes: {{ $value | humanize }}B/sec"
    - alert: catalogd-memory-growth
      expr: deriv(sum(container_memory_working_set_bytes{pod=~"catalogd.*",container="manager"})[5m:]) > 100_000
      for: 5m
      keep_firing_for: 1d
      annotations:
        description: "catalogd pod memory usage growing at a high rate for 5 minutes: {{ $value | humanize }}B/sec"
    - alert: operator-controller-memory-usage
      expr: sum(container_memory_working_set_bytes{pod=~"operator-controller.*",container="manager"}) > 100_000_000
      for: 5m
      keep_firing_for: 1d
      annotations:
        description: "operator-controller pod using high memory resources for the last 5 minutes: {{ $value | humanize }}B"
    - alert: catalogd-memory-usage
      expr: sum(container_memory_working_set_bytes{pod=~"catalogd.*",container="manager"}) > 75_000_000
      for: 5m
      keep_firing_for: 1d
      annotations:
        description: "catalogd pod using high memory resources for the last 5 minutes: {{ $value | humanize }}B"
    - alert: operator-controller-cpu-usage
      expr: rate(container_cpu_usage_seconds_total{pod=~"operator-controller.*",container="manager"}[5m]) * 100 > 20
      for: 5m
      keep_firing_for: 1d
      annotations:
        description: "operator-controller using high cpu resource for 5 minutes: {{ $value | printf \"%.2f\" }}%"
    - alert: catalogd-cpu-usage
      expr: rate(container_cpu_usage_seconds_total{pod=~"catalogd.*",container="manager"}[5m]) * 100 > 20
      for: 5m
      keep_firing_for: 1d
      annotations:
        description: "catalogd using high cpu resources for 5 minutes: {{ $value | printf \"%.2f\" }}%"
    - alert: operator-controller-api-call-rate
      expr: sum(rate(rest_client_requests_total{job=~"operator-controller-service"}[5m])) > 10
      for: 5m
      keep_firing_for: 1d
      annotations:
        description: "operator-controller making excessive API calls for 5 minutes: {{ $value | printf \"%.2f\" }}/sec"
    - alert: catalogd-api-call-rate
      expr: sum(rate(rest_client_requests_total{job=~"catalogd-service"}[5m])) > 5
      for: 5m
      keep_firing_for: 1d
      annotations:
        description: "catalogd making excessive API calls for 5 minutes: {{ $value | printf \"%.2f\" }}/sec"
