apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
# Pull in the experimental CRDs
resources:
- ../../../base/catalogd/crd/experimental
- ../../../base/catalogd/rbac/experimental
- ../../../base/catalogd/webhook/experimental
- ../../../base/operator-controller/crd/experimental
- ../../../base/operator-controller/rbac/experimental
# Pull in the component(s) common to standard and experimental
components:
- ../common
# EXPERIMENTAL FEATURES ARE LISTED HERE
- ../../features/webhook-provider-certmanager
- ../../features/single-own-namespace
- ../../features/preflight-permissions
- ../../features/apiv1-metas-handler
- ../../features/helm-chart
- ../../features/boxcutter-runtime
# This one is downstream only, so we shant use it
# - ../../features/webhook-provider-openshift-serviceca
