---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: service
        namespace: __NAMESPACE_PLACEHOLDER__
        path: /mutate-olm-operatorframework-io-v1-clustercatalog
        port: 9443
    failurePolicy: Fail
    matchConditions:
      - expression: "'name' in object.metadata && (!has(object.metadata.labels) || !('olm.operatorframework.io/metadata.name' in object.metadata.labels) || object.metadata.labels['olm.operatorframework.io/metadata.name'] != object.metadata.name)"
        name: MissingOrIncorrectMetadataNameLabel
    name: inject-metadata-name.olm.operatorframework.io
    rules:
      - apiGroups:
          - olm.operatorframework.io
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - clustercatalogs
    sideEffects: None
    timeoutSeconds: 10