{{- if .Values.options.catalogd.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  annotations:
    {{- include "olmv1.annotations" . | nindent 4 }}
  labels:
    app.kubernetes.io/name: catalogd
    {{- include "olmv1.labels" . | nindent 4 }}
  name: catalogd-controller-manager
  namespace: {{ .Values.namespaces.olmv1.name }}
spec:
  egress:
    - {}
  ingress:
    - ports:
        - port: 7443
          protocol: TCP
        - port: 8443
          protocol: TCP
        - port: 9443
          protocol: TCP
  podSelector:
    matchLabels:
      control-plane: catalogd-controller-manager
  policyTypes:
    - Ingress
    - Egress
{{- end }}
