{{- if .Values.options.operatorController.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  annotations:
    {{- include "olmv1.annotations" . | nindent 4 }}
  labels:
    app.kubernetes.io/name: operator-controller
    {{- include "olmv1.labels" . | nindent 4 }}
  name: operator-controller-controller-manager
  namespace: {{ .Values.namespaces.olmv1.name }}
spec:
  egress:
    - {}
  ingress:
    - ports:
        - port: 8443
          protocol: TCP
  podSelector:
    matchLabels:
      control-plane: operator-controller-controller-manager
  policyTypes:
    - Ingress
    - Egress
{{- end }}
