# kustomization file for secure operator-controller
# DO NOT ADD A NAMESPACE HERE
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../base/operator-controller
- ../../../base/common
components:
- ../../../components/cert-manager/operator-controller
# ca must be last or other components will overwrite the namespaces
- ../../../components/cert-manager/ca

patches:
 - target:
      kind: Deployment
      name: operator-controller-controller-manager
   path: patches/dev-deployment.yaml
