- op: add
  path: /spec/template/spec/volumes/-
  value: {"name":"catalogserver-certs", "secret":{"secretName":"catalogd-catalogserver-cert"}}
- op: add
  path: /spec/template/spec/containers/1/volumeMounts/-
  value: {"name":"catalogserver-certs", "mountPath":"/var/certs"}
- op: add
  path: /spec/template/spec/containers/1/args/-
  value: "--tls-cert=/var/certs/tls.crt"
- op: add
  path: /spec/template/spec/containers/1/args/-
  value: "--tls-key=/var/certs/tls.key"