apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
namespace: olmv1-system
resources:
- resources/manager_cert.yaml
patches:
- target:
    kind: Deployment
    name: controller-manager
    labelSelector: control-plane=operator-controller-controller-manager
  path: patches/manager_deployment_cert.yaml
