{{- if .Values.options.catalogd.enabled }}
{{/* Probably want to include this as a file somehow */}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    {{- include "olmv1.annotations" . | nindent 4 }}
  labels:
    app.kubernetes.io/name: catalogd
    {{- include "olmv1.labels" . | nindent 4 }}
  name: catalogd-metrics-reader
rules:
  - nonResourceURLs:
      - /metrics
    verbs:
      - get
{{- end }}
