{{- if .Values.components.certManager.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  annotations:
    {{- include "olmv1.annotations" . | nindent 4 }}
  labels:
    app.kubernetes.io/name: olmv1
    {{- include "olmv1.labels" . | nindent 4 }}
  name: olmv1-cert
  namespace: {{ .Values.namespaces.olmv1.name }}
spec:
  dnsNames:
    - operator-controller-service.{{ .Values.namespaces.olmv1.name }}.svc
    - operator-controller-service.{{ .Values.namespaces.olmv1.name }}.svc.cluster.local
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: olmv1-ca
  privateKey:
    algorithm: ECDSA
    rotationPolicy: Always
    size: 256
  secretName: olmv1-cert
{{- end }}
