{{/* this is a common component */}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  annotations:
    {{- include "olmv1.annotations" . | nindent 4 }}
  labels:
    app.kubernetes.io/name: {{ include "olmv1.label.name" . }}
    {{- include "olmv1.labels" . | nindent 4 }}
  name: {{ include "component.name.prefix" . -}}default-deny-all-traffic
  namespace: {{ .Values.namespaces.olmv1.name }}
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
