{{- if .Values.options.e2e.enabled }}
apiVersion: v1
kind: Pod
metadata:
  annotations:
    {{- include "olmv1.annotations" . | nindent 4 }}
  labels:
    app.kubernetes.io/name: e2e
    {{- include "olmv1.labels" . | nindent 4 }}
  name: e2e-coverage-copy-pod
  namespace: {{ .Values.namespaces.olmv1.name }}
spec:
  containers:
    - command:
        - sleep
        - infinity
      image: busybox:1.36
      name: tar
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
      terminationMessagePolicy: FallbackToLogsOnError
      volumeMounts:
        - mountPath: /e2e-coverage
          name: e2e-coverage-volume
          readOnly: true
  restartPolicy: Never
  securityContext:
    runAsNonRoot: true
    runAsUser: 65532
    seccompProfile:
      type: RuntimeDefault
  volumes:
    - name: e2e-coverage-volume
      persistentVolumeClaim:
        claimName: e2e-coverage
        readOnly: true
{{- end }}
