{{- if and .Values.options.catalogd.enabled .Values.options.catalogd.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: catalogd-controller-manager
  namespace: {{ .Values.namespaces.olmv1.name }}
  labels:
    app.kubernetes.io/name: catalogd
    {{- include "olmv1.labels" . | nindent 4 }}
  annotations:
    {{- include "olmv1.annotations" . | nindent 4 }}
spec:
  {{- if .Values.options.catalogd.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.options.catalogd.podDisruptionBudget.minAvailable }}
  {{- end }}
  {{- if .Values.options.catalogd.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.options.catalogd.podDisruptionBudget.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      control-plane: catalogd-controller-manager
{{- end }}
