{{- if and .Values.options.operatorController.enabled .Values.options.operatorController.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: operator-controller-controller-manager
  namespace: {{ .Values.namespaces.olmv1.name }}
  labels:
    app.kubernetes.io/name: operator-controller
    {{- include "olmv1.labels" . | nindent 4 }}
  annotations:
    {{- include "olmv1.annotations" . | nindent 4 }}
spec:
  {{- if .Values.options.operatorController.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.options.operatorController.podDisruptionBudget.minAvailable }}
  {{- end }}
  {{- if .Values.options.operatorController.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.options.operatorController.podDisruptionBudget.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      control-plane: operator-controller-controller-manager
{{- end }}
