{{- if .Values.options.operatorController.enabled }}
{{/* Probably want to include this as a file somehow */}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    {{- include "olmv1.annotations" . | nindent 4 }}
  labels:
    app.kubernetes.io/name: catalogd
    {{- include "olmv1.labels" . | nindent 4 }}
  name: operator-controller-leader-election-rolebinding
  namespace: {{ .Values.namespaces.olmv1.name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: operator-controller-leader-election-role
subjects:
  - kind: ServiceAccount
    name: operator-controller-controller-manager
    namespace: {{ .Values.namespaces.olmv1.name }}
{{- end }}
