{{- if .Values.options.openshift.enabled -}}
{{- if or .Values.options.catalogd.enabled .Values.options.operatorController.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  annotations:
    {{- include "olmv1.annotations" . | nindent 4 }}
  labels:
    openshift.io/cluster-monitoring: 'true'
    app.kubernetes.io/name: {{ include "olmv1.label.name" . }}
    {{- include "olmv1.labels" . | nindent 4 }}
  name: {{ include "olmv1.label.name" . -}}-metrics-monitor
  namespace: {{ .Values.namespaces.olmv1.name }}
spec:
  endpoints:
    - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      interval: 30s
      path: /metrics
      port: metrics
      scheme: https
      tlsConfig:
        caFile: /etc/prometheus/configmaps/serving-certs-ca-bundle/service-ca.crt
        certFile: /etc/prometheus/secrets/metrics-client-certs/tls.crt
        keyFile: /etc/prometheus/secrets/metrics-client-certs/tls.key
        serverName: {{ include "olmv1.label.name" . -}}-service.{{ .Values.namespaces.olmv1.name }}.svc
  namespaceSelector:
    matchNames:
      - {{ .Values.namespaces.olmv1.name }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "olmv1.label.name" . }}
  serviceDiscoveryRole: EndpointSlice
{{- end -}}
{{- end -}}
