---

apiVersion: core.olm.io/v1alpha1
kind: Operator
metadata:
  name: crossplane-highest-semver
spec:
  # Note: there's no spec.package.version field
  # configured here. The Operator controller will
  # attempt to find the highest semver bundle in
  # the configured spec.catalog catalog source.
  package:
    name: universal-crossplane
  source:
    type: "catalog"
    catalog:
      name: operatorhubio-catalog
      namespace: olm
