            {
              "apiVersion": "postgresql.cnpg.io/v1",
              "kind": "ScheduledBackup",
              "metadata": {
                "name": "scheduledbackup-sample"
              },
              "spec": {
                "cluster": {
                  "name": "cluster-sample"
                },
                "schedule": "0 0 0 * * *"
              }
            }
