{{- if .Values.options.certManager.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  annotations:
    {{- include "olmv1.annotations" . | nindent 4 }}
  labels:
    app.kubernetes.io/name: catalogd
    {{- include "olmv1.labels" . | nindent 4 }}
  name: catalogd-service-cert
  namespace: {{ .Values.namespaces.olmv1.name }}
spec:
  dnsNames:
    - localhost
    - catalogd-service.{{ .Values.namespaces.olmv1.name }}.svc
    - catalogd-service.{{ .Values.namespaces.olmv1.name }}.svc.cluster.local
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: olmv1-ca
  privateKey:
    algorithm: ECDSA
    rotationPolicy: Always
    size: 256
  secretName: catalogd-service-cert-git-version
{{- end }}
