apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/part-of: olm
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/enforce-version: "v1.32"
  name: system
