apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/part-of: olm
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: latest
  name: olmv1-system
