apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
namespace: olmv1-system
namePrefix: catalogd-
resources:
- resources/certificate.yaml
patches:
- target:
    kind: Service
    name: catalogserver
  path: patches/catalogserver_service_port.yaml
- target:
    kind: Deployment
    name: controller-manager
  path: patches/manager_deployment_certs.yaml
- target:
    group: admissionregistration.k8s.io
    kind: MutatingWebhookConfiguration
    name: mutating-webhook-configuration
    version: v1
  path: patches/catalogd_webhook.yaml
