apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: operator-controller-controller-manager
  name: controller-manager-metrics-service
  namespace: system
spec:
  ports:
  - name: https
    port: 8445
    protocol: TCP
    targetPort: 8445
  selector:
    control-plane: operator-controller-controller-manager
