# experimental values for OLMv1.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# List of enabled experimental features for operator-controller
# Use with {{- if has "FeatureGate" .Values.options.operatorController.features.enabled }}
# to pull in resources or additions
options:
  operatorController:
    features:
      enabled:
        - PreflightPermissions
        - HelmChartSupport
        - BoxcutterRuntime
      disabled:
        - WebhookProviderOpenshiftServiceCA
# List of enabled experimental features for catalogd
# Use with {{- if has "FeatureGate" .Values.options.catalogd.features.enabled }}
# to pull in resources or additions
  catalogd:
    features:
      enabled:
        - APIV1MetasHandler
# This can be one of: standard or experimental
  featureSet: experimental
