# experimental values for OLMv1.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Tilt is an exception to the multi-values case,
# as the Tilt runner only accepts a single values file

options:
  certManager:
    enabled: true
  tilt:
    enabled: true
  featureSet: experimental
  operatorController:
    features:
      enabled:
        - PreflightPermissions
        - HelmChartSupport
      disabled:
        - WebhookProviderOpenshiftServiceCA
  catalogd:
    features:
      enabled:
        - APIV1MetasHandler
