# kustomization file for all the e2e's
# DO NOT ADD A NAMESPACE HERE
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/catalogd
- ../../base/operator-controller
- ../../base/common
components:
- ../../components/tls/catalogd
- ../../components/tls/operator-controller
- ../../components/e2e
# ca must be last or other components will overwrite the namespaces
- ../../components/tls/ca
