---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.11.4
  name: packages.catalogd.operatorframework.io
spec:
  group: catalogd.operatorframework.io
  names:
    kind: Package
    listKind: PackageList
    plural: packages
    singular: package
  scope: Cluster
  versions:
  - name: v1beta1
    schema:
      openAPIV3Schema:
        description: Package is the Schema for the packages API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: PackageSpec defines the desired state of Package
            properties:
              catalogSource:
                description: CatalogSource is the name of the CatalogSource this package
                  belongs to
                type: string
              catalogSourceDisplayName:
                type: string
              catalogSourcePublisher:
                type: string
              channels:
                description: Channels are the declared channels for the package, ala
                  `stable` or `alpha`.
                items:
                  description: PackageChannel defines a single channel under a package,
                    pointing to a version of that package.
                  properties:
                    entries:
                      description: Entries is all the channel entries within a channel
                      items:
                        properties:
                          name:
                            type: string
                          replaces:
                            type: string
                          skipRange:
                            type: string
                          skips:
                            items:
                              type: string
                            type: array
                        required:
                        - name
                        type: object
                      type: array
                    name:
                      description: Name is the name of the channel, e.g. `alpha` or
                        `stable`
                      type: string
                  required:
                  - entries
                  - name
                  type: object
                type: array
              defaultChannel:
                description: DefaultChannel is, if specified, the name of the default
                  channel for the package. The default channel will be installed if
                  no other channel is explicitly given. If the package has a single
                  channel, then that channel is implicitly the default.
                type: string
              description:
                description: Description is the description of the package
                type: string
              icon:
                description: Icon is the Base64data image of the package for console
                  display
                properties:
                  base64data:
                    type: string
                  mediatype:
                    type: string
                type: object
            required:
            - catalogSource
            - channels
            - defaultChannel
            - description
            type: object
          status:
            description: PackageStatus defines the observed state of Package
            type: object
        type: object
    served: true
    storage: true
