name: catalogd-go-verdiff
on:
  pull_request:
    paths:
    - '**.mod'
    branches:
    - main
jobs:
  go-verdiff:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Check golang version
      working-directory: catalogd
      run: hack/scripts/check-go-version.sh "${{ github.event.pull_request.base.sha }}"
