on:
  pull_request:
    paths:
    - '.bingo/**'
    - '.github/workflows/tilt.yaml'
    - 'api/**'
    - 'cmd/**'
    - 'config/**'
    - 'catalogd/**'
    - 'internal/**'
    - 'pkg/**'
    - 'Tiltfile'
    - '.tilt-support'
  merge_group:

jobs:
  tilt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
      with:
        path: operator-controller
    - name: Install Go
      uses: actions/setup-go@v6
      with:
        go-version-file: "operator-controller/go.mod"
    - name: Install Tilt
      run: |
        TILT_VERSION="0.36.3"
        curl -fsSL https://github.com/tilt-dev/tilt/releases/download/v$TILT_VERSION/tilt.$TILT_VERSION.linux.x86_64.tar.gz | \
          tar -xzv -C /usr/local/bin tilt
    - name: Set up kind
      run: |
        cd operator-controller
        make kind-cluster
    - name: Test Tilt
      run: |
        cd operator-controller
        tilt ci
