name: unit-test

on:
  workflow_dispatch:
  pull_request:
  merge_group:
  push:
    branches:
    - main

jobs:
  unit-test-basic:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v6

    - uses: actions/setup-go@v6
      with:
        go-version-file: go.mod

    - name: Run basic unit tests
      run: |
        make test-unit

    - uses: codecov/codecov-action@v5.5.2
      with:
        disable_search: true
        files: coverage/unit.out
        flags: unit
        token: ${{ secrets.CODECOV_TOKEN }}
